## name: Vivid
## license: MIT

# Misc
background #000000
foreground #FFFFFF
selection_background #FFFFFF
cursor #FFFFFF

# Black
color0  #000000
color8  #677180

# Red
color1  #FF1A41
color9  #FF6289

# Green
color2  #00FF34
color10 #95FFAB

# Yellow
color3  #FFD700
color11 #FFEC6E

# Blue
color4  #0077F7
color12 #00AAFF

# Magenta (Purple)
color5  #B624FF
color13 #E45BFF

# Cyan
color6  #009DA6
color14 #33FFFF

# White
color7  #CFD9E5
color15 #F2F2F2
