## name: Vivid
## license: MIT

background                #000000
foreground                #b2b2b2

selection_background      #444444
selection_foreground      #ffffff

cursor                    #b2b2b2
cursor_text_color         #000000

url_color                 #0070f0

wayland_titlebar_color    background
macos_titlebar_color      system

active_border_color       #686868
inactive_border_color     #181818
bell_border_color         #ff5757
visual_bell_color         none

active_tab_background     #444444
active_tab_foreground     #ffffff
inactive_tab_background   #181818
inactive_tab_foreground   #686868
tab_bar_background        none
tab_bar_margin_color      none

color0                    #000000
color1                    #e03030
color2                    #20d030
color3                    #e0a000
color4                    #0037e0
color5                    #b020b0
color6                    #30b0b0
color7                    #b2b2b2

color8                    #686868
color9                    #ff5757
color10                   #54ff54
color11                   #ffd92e
color12                   #0070f0
color13                   #ff54ff
color14                   #54ffff
color15                   #ffffff
